// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaVtyJ7Qf7K58Ac-o8xceVax1XBAegmuo',
    appId: '1:682988493187:web:311e3462168fd49cd83eb6',
    messagingSenderId: '682988493187',
    projectId: 'instagrampa-409c1',
    authDomain: 'instagrampa-409c1.firebaseapp.com',
    storageBucket: 'instagrampa-409c1.appspot.com',
    measurementId: 'G-7C5R5V3CD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3ngnSI7FLdorSk9bzYLt7yyK-JnJAYQ',
    appId: '1:682988493187:android:2addedc7f08d8bd4d83eb6',
    messagingSenderId: '682988493187',
    projectId: 'instagrampa-409c1',
    storageBucket: 'instagrampa-409c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB2G5F6dFs-DRyEURze5B4uBTmmiIdYr8',
    appId: '1:682988493187:ios:3b8a0e9932ed7a57d83eb6',
    messagingSenderId: '682988493187',
    projectId: 'instagrampa-409c1',
    storageBucket: 'instagrampa-409c1.appspot.com',
    iosBundleId: 'com.example.instagramPa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB2G5F6dFs-DRyEURze5B4uBTmmiIdYr8',
    appId: '1:682988493187:ios:6f85a68c23b0bb9fd83eb6',
    messagingSenderId: '682988493187',
    projectId: 'instagrampa-409c1',
    storageBucket: 'instagrampa-409c1.appspot.com',
    iosBundleId: 'com.example.instagramPa.RunnerTests',
  );
}
